<?php

/**
 * @name IndexController
 * @author wangjin
 * @desc 默认控制器
 */


class IndexController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 网站首页入口
     */
    public function indexAction()
    {
        $this->assign['pagetitle'] = 'Yaf_Demo';
        echo $this->twig->render('index/index.twig', $this->assign);
    }
}
