<?php

/**
 * @name IndexController
 * @author root
 * @desc 默认控制器
 */


class IndexController extends BaseController
{
    private $db = null;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = Yaf_Registry::get('db');
    }

    /**
     * 网站首页入口
     */
    public function indexAction()
    {
        $assign = array();
        $assign['pagetitle'] = '斗图';
        // 获取恶搞图片列表
        $eglist = $this->db->query('SELECT `id`, `title`, `titlepic`, `oncreate` FROM `eg_list` ORDER BY RAND() LIMIT 12')->fetchAll();
        $assign['eglist'] = $eglist;
        echo $this->twig->render('index/index.php', $assign);
    }
}
