<?php

/**
 * @name IndexController
 * @author wangjin
 * @desc 默认控制器
 */


class IndexController extends BaseController
{
    private $db = null;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = Yaf_Registry::get('db');
    }

    /**
     * 网站首页入口
     */
    public function indexAction()
    {
        $assign = array(
            'pagetitle' => 'Yaf'
        );
        echo $this->twig->render('index/index.php', $assign);
    }
}
