<?php

/**
 * Created by PhpStorm.
 * User: wangjin
 * Date: 2017/9/7
 * Time: 下午3:03
 */
class UserController extends BaseController
{
    private $db = null;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = Yaf_Registry::get('db');
    }

    /**
     * 微信一键登录,注册
     */
    public function registerAction()
    {
        $channelid = Help::getg('openid');
        $channelid = Help::randStr(16);
        if(empty($channelid))
        {
            die('参数错误');
        }
        // 检索用户信息
        $user = $this->db->select('sys_client', ['id', 'nickname', 'birthday', 'sex', 'province', 'city', 'area'], ['channelid' => $channelid])[0];
        // 注册用户 insert into sys_client(username, channelid) values('1001', '1001')
        if(empty($user)){
            $regdate  = Help::hdate('Y-m-d H:i:s', time());
            $this->db->insert("sys_client", [
                'username' => $channelid,
                'channelid' => $channelid,
                'regdate' => $regdate,
                'lastlogintime' => $regdate,
            ]);
            $lastid = $this->db->id();
            echo $lastid;
            die;
        }
        die('success');
    }
    /**
     * 完善用户信息
     */
    public function editAction()
    {
        $uid = intval( Help::getg('uid') );
        // 读取用户数据
        $user = $this->db->select('sys_client', ['id', 'nickname', 'birthday', 'sex', 'province', 'city', 'area'], ['id' => 8])[0];
        //print_r($user);
        // view
        $this->getView()->assign("user", $user);
    }

    /**
     * 用户信息保存
     */
    public function userSaveAction()
    {
        $p = array();
        if (!empty($_FILES['upfile']['tmp_name'])) {
            // 大图
            $p['avatar_big'] = Help::upload('upfile', 'upload'); // 表单name, 上传目录
            $file = PUBLIC_PATH . $p['avatar_big'];
            $thumb_file = $file . '_thumb.jpg';
            // 生成缩略图
            $res = ImageManager::thumbnail($file, $thumb_file, 200);
            if ($res) {
                $p['avatar'] = $thumb_file;
            }
        }
        // ID
        $id = Help::getp('id');
        // 名字
        $p['nickname'] = Help::getp('nickname');
        // 性别
        $p['sex'] = Help::getp('sex');
        // 生日
        $p['birthday'] = Help::getp('birthday');
        // 省
        $p['province'] = Help::getp('province');
        // 市
        $p['city'] = Help::getp('city');
        // 区
        $p['birthday'] = Help::getp('birthday');
        // 开始更新
        $res = $this->db->update('sys_client', $p, array(
            'id' => $id
        ));
        if($res){
            $this->redirect('/user/edit');
        }else{
            die('error');
        }

        return false;
    }


}